# Generated by Django 4.1.2 on 2022-10-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150, verbose_name='Brand nomi')),
                ('model', models.CharField(max_length=150, verbose_name='Modeli')),
                ('color', models.CharField(max_length=100, verbose_name='Rangi')),
                ('number', models.CharField(max_length=150, verbose_name='Mashina raqami')),
            ],
        ),
    ]
