# Generated by Django 4.1.2 on 2022-10-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Xaydovchi ismi')),
                ('last_name', models.CharField(max_length=150, verbose_name='Xaydovchi Familiyasi')),
                ('car', models.CharField(max_length=150, verbose_name='Mashina')),
            ],
        ),
    ]
